title: Your awesome title
description: > # this means to ignore newlines until "show_excerpts:"
  <img src="https://www.easycounter.com/counter.php?lufficc" alt="number visitors"> unique visitors since July 2019.

remote_theme: jekyll/minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
